### PR TITLE
docs: use stable diffusion as an example in the readme

### PR DESCRIPTION
**Pull request by kemingy**
This example is an advanced usage. But I think stable diffusion is much more attractive.

We should try to show the ability to serve modern models like stable diffusion, GPT, etc.

### CODE REVIEW

**Review by gaocegege — DISMISSED** [review]

**Comment by lkevinzc** [comment]
My concern is that if such example is easy to run on any machine (without GPU), e.g., an old mac.

**Comment by lkevinzc** [comment]
> My concern is that if such example is easy to run on any machine (without GPU), e.g., an old mac.

Then, maybe need to add a few lines stating the dependency installation for convenience.

**Comment by kemingy** [comment]
> My concern is that if such example is easy to run on any machine (without GPU), e.g., an old mac.

I see. Maybe we can add annotations to the `examples` section about which can be run on CPU. Users can try that one as a simple demo.

**Comment by lkevinzc** [comment]
> > My concern is that if such example is easy to run on any machine (without GPU), e.g., an old mac.
> 
> I see. Maybe we can add annotations to the `examples` section about which can be run on CPU. Users can try that one as a simple demo.

I feel that examples in README should be easy to understand, while demonstrating the core functionality. Diffusion model inference code might not look familiar to people who are working in other fields.

To make the readme attractive we might:
1) add some GIF demonstrating querying a mosec server hosting diffusion models (and other popular or interesting use cases)
2) highlight use cases such as recent MOSS

But definitely we can replace the current example with others, we shall discuss a bit more on this.

**Comment by kemingy** [comment]
> I feel that examples in README should be easy to understand at the first glance, while demonstrating the core functionality. Diffusion model inference code might not look familiar to people who are working in other fields.
> 
> To make the readme attractive we might:
> 
>     1. add some GIF demonstrating querying a mosec server hosting diffusion models (and other popular or interesting use cases)
> 
>     2. highlight use cases such as recent MOSS
> 
> 
> But definitely we can replace the current example with others, we shall discuss a bit more on this.

Refer to https://github.com/mosecorg/mosec/issues/200

It's hard to have a simple example with all the following features:
- easy to understand
- attractive models
- dynamic batching
- CPU & GPU pipeline
- integration with other famous tools

Most people won't look at the examples folder or the documentation page. I think an attractive example should be very important to get people interested in exploring more.

**Comment by lkevinzc** [comment]
> Refer to #200
> 
> It's hard to have a simple example with all the following features:
> 
> * easy to understand
> * attractive models
> * dynamic batching
> * CPU & GPU pipeline
> * integration with other famous tools
> 
> Most people won't look at the examples folder or the documentation page. I think an attractive example should be very important to get people interested in exploring more.

Okay, then it looks good

**Review by lkevinzc — APPROVED** [review]

**Pull request merged**
