### PR TITLE
feat: use pyproject for configs

### PR DESCRIPTION
**Pull request by kemingy**

### CODE REVIEW

**Comment by kemingy** [comment]
Cannot delete `setup.cfg` since `flake8` doesn't support pyproject config.

Maybe we can try `pylint`?

**Comment by lkevinzc** [comment]
> Cannot delete `setup.cfg` since `flake8` doesn't support pyproject config.
> 
> Maybe we can try `pylint`?

Will it cause too many formatting changes?

**Comment by kemingy** [comment]
> > Cannot delete `setup.cfg` since `flake8` doesn't support pyproject config.
> > Maybe we can try `pylint`?
> 
> Will it cause too many formatting changes?

```
Messages
--------

+-----------------------------+------------+
|message id                   |occurrences |
+=============================+============+
|missing-module-docstring     |10          |
+-----------------------------+------------+
|invalid-name                 |9           |
+-----------------------------+------------+
|protected-access             |7           |
+-----------------------------+------------+
|missing-function-docstring   |6           |
+-----------------------------+------------+
|no-self-use                  |4           |
+-----------------------------+------------+
|broad-except                 |3           |
+-----------------------------+------------+
|too-many-arguments           |2           |
+-----------------------------+------------+
|raise-missing-from           |2           |
+-----------------------------+------------+
|too-many-instance-attributes |1           |
+-----------------------------+------------+
|too-few-public-methods       |1           |
+-----------------------------+------------+
|redefined-builtin            |1           |
+-----------------------------+------------+
|pointless-string-statement   |1           |
+-----------------------------+------------+
|missing-class-docstring      |1           |
+-----------------------------+------------+
|consider-using-with          |1           |
+-----------------------------+------------+
```

**Comment by lkevinzc** [comment]
> > > Cannot delete `setup.cfg` since `flake8` doesn't support pyproject config.
> > > Maybe we can try `pylint`?
> > 
> > 
> > Will it cause too many formatting changes?
> 
> ```
> Messages
> --------
> 
> +-----------------------------+------------+
> |message id                   |occurrences |
> +=============================+============+
> |missing-module-docstring     |10          |
> +-----------------------------+------------+
> |invalid-name                 |9           |
> +-----------------------------+------------+
> |protected-access             |7           |
> +-----------------------------+------------+
> |missing-function-docstring   |6           |
> +-----------------------------+------------+
> |no-self-use                  |4           |
> +-----------------------------+------------+
> |broad-except                 |3           |
> +-----------------------------+------------+
> |too-many-arguments           |2           |
> +-----------------------------+------------+
> |raise-missing-from           |2           |
> +-----------------------------+------------+
> |too-many-instance-attributes |1           |
> +-----------------------------+------------+
> |too-few-public-methods       |1           |
> +-----------------------------+------------+
> |redefined-builtin            |1           |
> +-----------------------------+------------+
> |pointless-string-statement   |1           |
> +-----------------------------+------------+
> |missing-class-docstring      |1           |
> +-----------------------------+------------+
> |consider-using-with          |1           |
> +-----------------------------+------------+
> ```

The suggestion messages look nice!

**Comment by lkevinzc** [comment]
Shall we go for `pylint` in this MR?

**Comment by kemingy** [comment]
> Shall we go for `pylint` in this MR?

Too many changes are required. Let's create another PR to fix it.

**Review by lkevinzc — APPROVED** [review]

**Pull request merged**
