### PR TITLE
feat: lint with pyright

### LINKED ISSUE #176: `mypy` is annoying, let's switch to `pyright`
`mypy` is annoying, let's switch to `pyright`

_Originally posted by @kemingy in https://github.com/mosecorg/mosec/issues/175#issuecomment-1162618549_

### PR DESCRIPTION
**Pull request by kemingy**
* fix #176 
* both `mypy` and `pyright` are kept here, I wonder if we should find a way to `make type-lint` success when at least one of `mypy` and `pyright` works

### CODE REVIEW

**Comment by kemingy** [comment]
BTW, `pydantic` is using both https://github.com/pydantic/pydantic/blob/f2c3a49d662378998dd1962fe0ca0ec160a7ad53/.github/workflows/ci.yml#L63

**Comment by kemingy** [comment]
* PS: in my new dev env, the `pre-commit-hook` always failed on `mypy`

**Review by lkevinzc — APPROVED** [review]
Sorry for the delayed review, LGTM!

**Comment by kemingy** [comment]
Just to note here:

Make sure at least one type check is passed. If `mypy` still failed, I will use the following command.

```make
type_lint:
	@-rm mosec/_version.py
	@pyright --stats;\
	if [ $$? -ne 0 ]; then \
		echo "pyright failed, try to use mypy"; \
		mypy --non-interactive --install-types ${PY_SOURCE_FILES}; \
	else \
		echo "pyright succeed, check mypy but ignore the result"; \
		mypy --non-interactive --install-types ${PY_SOURCE_FILES} || true; \
	fi
```

**Comment by lkevinzc** [comment]
> 

Got it!

**Comment by lkevinzc** [comment]
> Just to note here:
> 
> Make sure at least one type check is passed. If `mypy` still failed, I will use the following command.
> 
> ```makefile
> type_lint:
> 	@-rm mosec/_version.py
> 	@pyright --stats;\
> 	if [ $$? -ne 0 ]; then \
> 		echo "pyright failed, try to use mypy"; \
> 		mypy --non-interactive --install-types ${PY_SOURCE_FILES}; \
> 	else \
> 		echo "pyright succeed, check mypy but ignore the result"; \
> 		mypy --non-interactive --install-types ${PY_SOURCE_FILES} || true; \
> 	fi
> ```

Got it!

**Pull request merged**
