### PR TITLE
feat: Support multi-route in mosec

### LINKED ISSUE #355: feat: Support multi-route in mosec
### Describe the feature

Support multi-route in mosec

```
/chat/completions --> worker1
/completions --> worker2
```

### Why do you need this feature?

Support https://github.com/tensorchord/modelz-llm

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cutecutecat**
close #355

### CODE REVIEW

**Comment by VoVAllen** [comment]
Is it possible for user to change the  config of a llm (such as change the prompt), through endpoint like `/chatglm/config`?

**Review by lkevinzc — COMMENTED** [review]
some minor typos

**Comment by cutecutecat** [comment]
> some minor typos

Thanks, fixed.

**Comment by cutecutecat** [comment]
> Seems that this PR supports multi-route by adding a pipeline of workers to a specified route, and different pipelines work independently. If so, my question is why don't we move such complexity out from a single service - using a gateway to route before individual mosec servers which host their own pipelines - this can also easily share the workload resources of individual mosec servers, by writing flexible logic inside the gateway.

Thanks for your reply, this enhancement would introduce a external gateway, and it should be high-performance enough. I have done a survey of candidates:

- nginx
- Rust-based gateway silverwind https://github.com/lsk569937453/silverwind
- C++-based gateway envoy https://github.com/envoyproxy/envoy

To achieve this, I think we need to dynamically generate a config arguments/file of gateway at  `_start_controller` of server.py and make it a daemon, so the config need to be easily to generate by program.
❌nginx - horrible *.conf

Then, as the gateway should be packeted and controlled by `Mosec`, it should be carried out by code and compiled at install, like `src/*`, maybe by git submodule.
❌envoy - need a C++ compile toolchain

silverwind seems ok but it's a personal project, I am not sure whether it would be continuously maintained. Is it fine to introduce into Mosec? If you have any other ideas, I am happy to hear.

**Review by kemingy — COMMENTED** [review]
Sorry for the late review. I only checked the main Python code (excluding the dry run logic). I feel it lacks abstraction. This makes the code even worse. This part might need to rethink about the design.

**Comment by kemingy** [comment]
> silverwind seems ok but it's a personal project, I am not sure whether it would be continuously maintained. Is it fine to introduce into Mosec? If you have any other ideas, I am happy to hear.

There are lots of reverse proxy projects in Rust. But I don't plan to include that in mosec. If we're going this way, a docker-compose demo would be better since packaging other binary requires reviewing the LICENSE.

**Comment by cutecutecat** [comment]
I would close this for not support multi routes but dynamic routes by https://github.com/mosecorg/mosec/issues/355#issuecomment-1556812045 .

**Pull request closed without merging**
